### ISSUE TITLE
API 서버 개발

### ISSUE THREAD

**Issue by sogoagain** [CodeSoom/project-react-1-sogoagain#13]

**Comment by sogoagain** [comment]
AWS Lambda와 DynamoDB를 이용한 API 서버 개발이 완료되었습니다.

**Comment by hannut91** [comment]
API 서버 코드도 같이 올라와 있으면 좋을 것 같네요!

**Comment by sogoagain** [comment]
> API 서버 코드도 같이 올라와 있으면 좋을 것 같네요!

같이 올릴지 말지 고민이 되었는데, 일단 리액트 프로젝트가 아니라... 개인 저장소에서 작업했습니다! 아래의 링크에서 코드를 확인하실 수 있습니다.

[idea-box-api](https://github.com/sogoagain/idea-box-api)

**Comment by hannut91** [comment]
포폴로 사용하려면 같이 있는게 좋을 것 같아요 ㅎㅎ

**Comment by sogoagain** [comment]
> 포폴로 사용하려면 같이 있는게 좋을 것 같아요 ㅎㅎ 혹은 링크를 README남겨도 괜챃을 것 같아요

그렇지 않아도 두 개의 프로젝트를 어떻게 관리하면 좋을까 고민하고 있었어요. 
합치려고 하니 CI/CD 설정과 git 커밋 로그가 섞이는 것이 마음에 걸려 각 프로젝트 README에 링크를 남겨보도록 하겠습니다. :)
감사합니다 👍
