### ISSUE TITLE
사용자는 다양한 아이디어를 구성하기 위해 어떤 사람을 위한 것인지 제안할 수 있다.

### ISSUE THREAD

**Issue by sogoagain** [CodeSoom/project-react-1-sogoagain#7]

**Comment by wholemann** [comment]
사용자 스토리를 따로 공부하셨나요?

훌륭하네요.

**Comment by sogoagain** [comment]
> 사용자 스토리를 따로 공부하셨나요?
> 
> 훌륭하네요.
> 
> 다만 `${누구}` 같은 표현은 기술적인 접근이기 때문에 사용자 스토리에선 표현되지 않는게 좋습니다.

그렇네요. 너무 기술적으로 생각해서 작성한 것 같습니다. 👍 
사용자 관점으로 고민해서 바꿔보았어요.
